### ISSUE TITLE
In the CONTRIBUTING.md documentation it mentions fork on "master" but the repository is pointing to "main".

### ISSUE THREAD

**Issue by Paulo-Lopes-Estevao** [antonio-nicolau/ClientAO#1]
Hi there 😊 we're super happy to know that you're using ClientAO! Please feel free to fill the form below and let us know what bug you're facing

**Describe the bug**
The branch name of the main repository is "main" and the Contribution documentation mentions fork on "master".

**Screenshots**
<img width="443" alt="Screenshot 2023-04-25 at 23 22 21" src="https://user-images.githubusercontent.com/66704496/234417221-a3d8a2e0-838d-4a2f-98e9-27ee31ce7216.png">

I suggest a correction in the name in which the main repository points.

**Comment by antonionicolau** [comment]
Hi @Paulo-Lopes-Estevao eagle eyes 👀 really thank you for bringing this up, I'm going to update those templates 🙂

**Comment by antonio-nicolau** [comment]
Hi @Paulo-Lopes-Estevao eagle eyes 👀 really thank you for bringing this up, I'm going to update those templates 🙂

**Comment by antonio-nicolau** [comment]
This "master" was updated here #2
