### ISSUE TITLE
I suggest using MAP contrary switch to declare HTTP calls

### ISSUE THREAD

**Issue by Paulo-Lopes-Estevao** [antonio-nicolau/ClientAO#3]
**Is your feature request related to a problem? Please describe.**
While the current code may work well for the simple application that makes only a few HTTP calls, more it may become difficult to maintain and scale as the complexity of the application increases.

**Describe the solution you'd like**
I intend to add a MAP data structure to store the functions corresponding to each HTTP method, this allows you to add support for new HTTP methods without changing existing code, just add a new entry to Map.

```dart
final methodHandlers = <HttpVerb, Future<Response>>{
      HttpVerb.get: _httpClient.get(uri!, headers: headers),
      HttpVerb.post: _httpClient.post(uri!, headers: headers, body: body),
      HttpVerb.put: _httpClient.put(uri!, headers: headers, body: body),
      HttpVerb.patch: _httpClient.patch(uri!, headers: headers, body: body),
      HttpVerb.delete: _httpClient.delete(uri!, headers: headers, body: body),
  };
```

**Describe alternatives you've considered**

I have considered in the future using function or methods for each method, making the code reusable for more complex functions, you may consider creating an abstract interface or class that defines a common set of methods or properties that can be implemented or extended by specific classes.

example:
```dart
abstract class HttpClient {
  Future<Response> get(Uri url, {Map<String, String>? headers});
}

class RequestHttpClient implements HttpClient {
@override
  Future<Response> get(Uri url, {Map<String, String>? headers}) async {
    return get(url.toString(), options: Options(headers: headers));
  }

}
```
This implementation can make the code more scalable and reusable for more complex functions in the future.

**Comment by antonio-nicolau** [comment]
Nice suggestion :) thanks for fill this issue

**Comment by antonio-nicolau** [comment]
Nice refactoring 😀 while reading your code some ideas came up, 
what if instead of have this `_methodHandlers` inside `request` method, we export that into a separated method e.g `doRequest` giving corrects params like `httpClient, method, uri, headers and body`. This way we have a more reusable and scalable code.

`doRequest` (exported _methodHandlers outside `request` method)

```dart
Future<Response> doRequest({required HttpVerb method,required CustomHttpClient httpClient,required Uri? uri,Map<String,String>? headers,String? body,})async{

    if(uri == null) throw Exception('Uri cannot be null');

    final methodHandlers = <HttpVerb, Future<Response>>{
      HttpVerb.get: httpClient.get(uri, headers: headers??{}),
      HttpVerb.post: httpClient.post(uri, headers: headers, body: body),
      HttpVerb.put: httpClient.put(uri, headers: headers, body: body),
      HttpVerb.patch: httpClient.patch(uri, headers: headers, body: body),
      HttpVerb.delete: httpClient.delete(uri, headers: headers, body: body),
    };

     if (!methodHandlers.containsKey(method)) {
      throw UnsupportedError('Unsupported HTTP method: $method');
    }

    

    return methodHandlers[method]!;
  }
```

New `request` method (just calling `doRequest`)

```dart
final response = await doRequest(method:request.method,httpClient: _httpClient,
      uri: uri,
      headers: headers,
      body: body,
      );
```

We still can think about more refactoring, I liked the idea of having _a class that defines a common set of methods_ , this way we remove the `CustomHttpClient` from `ApiRequestRepository` and code become much better

**Comment by Paulo-Lopes-Estevao** [comment]
> Nice refactoring 😀 while reading your code some ideas came up, what if instead of have this `_methodHandlers` inside `request` method, we export that into a separated method e.g `doRequest` giving corrects params like `httpClient, method, uri, headers and body`. This way we have a more reusable and scalable code.
> 
> `doRequest` (exported _methodHandlers outside `request` method)
> 
> ```dart
> Future<Response> doRequest({required HttpVerb method,required CustomHttpClient httpClient,required Uri? uri,Map<String,String>? headers,String? body,})async{
> 
>     if(uri == null) throw Exception('Uri cannot be null');
> 
>     final methodHandlers = <HttpVerb, Future<Response>>{
>       HttpVerb.get: httpClient.get(uri, headers: headers??{}),
>       HttpVerb.post: httpClient.post(uri, headers: headers, body: body),
>       HttpVerb.put: httpClient.put(uri, headers: headers, body: body),
>       HttpVerb.patch: httpClient.patch(uri, headers: headers, body: body),
>       HttpVerb.delete: httpClient.delete(uri, headers: headers, body: body),
>     };
> 
>      if (!methodHandlers.containsKey(method)) {
>       throw UnsupportedError('Unsupported HTTP method: $method');
>     }
> 
>     
> 
>     return methodHandlers[method]!;
>   }
> ```
> 
> New `request` method (just calling `doRequest`)
> 
> ```dart
> final response = await doRequest(method:request.method,
>       httpClient: _httpClient,
>       uri: uri,
>       headers: headers,
>       body: body,
>       );
> ```
> 
> We still can think about more refactoring, I liked the idea of having _a class that defines a common set of methods_ , this way we remove the `CustomHttpClient` from `ApiRequestRepository` and code become much better

The idea is even better considering 👍🏼

**Comment by Paulo-Lopes-Estevao** [comment]
> > Nice refactoring 😀 while reading your code some ideas came up, what if instead of have this `_methodHandlers` inside `request` method, we export that into a separated method e.g `doRequest` giving corrects params like `httpClient, method, uri, headers and body`. This way we have a more reusable and scalable code.
> > `doRequest` (exported _methodHandlers outside `request` method)
> > ```dart
> > Future<Response> doRequest({required HttpVerb method,required CustomHttpClient httpClient,required Uri? uri,Map<String,String>? headers,String? body,})async{
> > 
> >     if(uri == null) throw Exception('Uri cannot be null');
> > 
> >     final methodHandlers = <HttpVerb, Future<Response>>{
> >       HttpVerb.get: httpClient.get(uri, headers: headers??{}),
> >       HttpVerb.post: httpClient.post(uri, headers: headers, body: body),
> >       HttpVerb.put: httpClient.put(uri, headers: headers, body: body),
> >       HttpVerb.patch: httpClient.patch(uri, headers: headers, body: body),
> >       HttpVerb.delete: httpClient.delete(uri, headers: headers, body: body),
> >     };
> > 
> >      if (!methodHandlers.containsKey(method)) {
> >       throw UnsupportedError('Unsupported HTTP method: $method');
> >     }
> > 
> >     
> > 
> >     return methodHandlers[method]!;
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > New `request` method (just calling `doRequest`)
> > ```dart
> > final response = await doRequest(method:request.method,
> >       httpClient: _httpClient,
> >       uri: uri,
> >       headers: headers,
> >       body: body,
> >       );
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > We still can think about more refactoring, I liked the idea of having _a class that defines a common set of methods_ , this way we remove the `CustomHttpClient` from `ApiRequestRepository` and code become much better
> 
> The idea is even better considering 👍🏼

I just added the idea taking into account all the points raised [CODE](https://github.com/antonio-nicolau/ClientAO/pull/4/commits/70e113106b9393f16c05de2f6294594a209ba975)
