### ISSUE TITLE
I have a suggestion regarding using the main branch for all changes.

### ISSUE THREAD

**Issue by Paulo-Lopes-Estevao** [antonio-nicolau/ClientAO#6]
I suggest that the project has a branch `develop`, to have more control of the changes, project mentions the use of gitflow.
All changes first go to branch `develop` where they can be analyzed and tested.

When it was to make a `release` of a version you could also use gitflow we would have separate branches of the `releases` that were already made including the tags that will be generated
ex: **release/1.0.0 -> tag v1.0.0**

**Comment by antonio-nicolau** [comment]
Yes you're right following gitflow as mentioned in the CONTRIBUTION guideline we should have a develop/features branch.
Regarding releases branch we're already had releases/1.0.0 branch.
I'm going to create `develop` from `main` 👌🏿

Thanks for noticing that 🙂

**Comment by antonio-nicolau** [comment]
There's now a `develop` branch, all changes first go to **--> develop --> release --> main**
