### ISSUE TITLE
Add head method

### ISSUE THREAD

**Issue by Paulo-Lopes-Estevao** [antonio-nicolau/ClientAO#7]
**Is your feature request related to a problem? Please describe.**
The HEAD method is similar to GET, but is generally faster, because the server needs to send only the headers and not the body of the response, so we can consider its implementation necessary.

**Describe the solution you'd like**
I intend to add the HEAD method is useful when a client needs to check if a resource exists, if it is accessible, and if the server is available.

For example, a HEAD request before downloading a complete resource, to check if the resource is available and if the user has permission to access it. And many other cases that are also relevant to your implementation.

**Comment by antonio-nicolau** [comment]
Yes this method was missed out, thanks for adding. Keep it up 💪🏿
